### PR TITLE
:boom: Add collisions methods

### PR DESCRIPTION
**Pull request by landryarki**
collisions methods to collide boxes and spheres

### CODE REVIEW

**Review by Marius-P1 — COMMENTED** [review]
Sounds good to me, but I'm not a fan of the "VS" naming :eyes:

**Review by AubaneNourry — APPROVED** [review]
I agree with the functions but not sure about the use,
We will add components like RectCollider, RoundCollider that will use these functions in their inner logic and will refer to a Transform Component to get the position / dimensions of these geometrics elements?

**Review by 6im0n — APPROVED** [review]
Good for me ! :+1:

**Review by RenardFute — COMMENTED** [review]
I'm not going to approve or disapprove this.
I believe what you did is working, there is no problem with that but it looks like your system is really 'rigid'. What I mean by that is, that whenever we will want to add another X collide with Y we will need to update Physics::Collision class.
My idea would have been to make an ICollider interfaces that would provide some way of mathematically know wether it's colliding with something.
The result code in Physics::Collision would look like this
```C++
bool isColliding(const ICollider &a, const IColllider &b) {
  const aEquation = a.getCollisionEquation();
  const bEquation = b.getCollisionEquation();
  const mixed = // some math stuff
  return // math result
}
```
This is all theoretical but I believe, if possible, a system like this would be better.

Maybe SDF ??

**Review by Marius-P1 — APPROVED** [review]
:ok_hand:

**Review by RenardFute — CHANGES_REQUESTED** [review]
Can you just split your classes like don't put Sphere and Box Collider in the same file. Same for Physics.hpp

**Review by RenardFute — APPROVED** [review]

**Pull request merged**
